name: Run bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # her 30 dakikada bir çalışır (isteğe göre değiştirilebilir)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul  # Türkiye saati ile çalış

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright tweepy
          python -m playwright install --with-deps chromium

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python -u main.py
