name: KAP AutoTweet (Playwright)

on:
  workflow_dispatch:         # yalnızca dış tetik (cron-job.org). GitHub cron kapalı.
  # schedule:                # ❌ kapalı

permissions:
  contents: write

concurrency:
  group: kap-autotweet
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0        # rebase/pull için gerekli

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install tweepy playwright
          python -m playwright install --with-deps chromium

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py

      - name: Persist state.json (commit & push)
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            if ! git diff --staged --quiet; then
              git commit -m "chore: update state [skip ci]"
              # non-fast-forward hatasına karşı rebase/pull + retry
              git pull --rebase --autostash origin ${{ github.ref_name }} || true
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }} || \
              (git pull --rebase --autostash origin ${{ github.ref_name }} && \
               git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }})
            fi
          fi
