name: KAP AutoTweet (Playwright)

on:
  # İstersen sıklaştırıp seyrekleştirebilirsin (*/2 = 2 dakikada bir)
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu getir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          python -m pip install tweepy playwright
          python -m playwright install --with-deps chromium

      - name: Çalıştır
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py

      # Hata olursa ekran görüntüsü/HTML bırakmışsak indirmeye yarar (opsiyonel)
      - name: Debug çıktıları (varsa) yükle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kap-debug
          path: debug/
          if-no-files-found: ignore
