name: KAP AutoTweet (Playwright)

on:
  workflow_dispatch:         # cron-job.org bu endpoint'i çağırıyor (dispatches)
  # schedule:                # ❌ kapatıldı: GitHub kendi kendine tetiklemesin

permissions:
  contents: write

concurrency:
  group: kap-autotweet
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu getir
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          python -m pip install tweepy playwright
          python -m playwright install --with-deps chromium

      - name: Botu çalıştır
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py

      - name: state.json’ı kalıcılaştır (commit & push)
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            if ! git diff --staged --quiet; then
              git commit -m "chore: update state [skip ci]"
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
            fi
          fi
