name: KAP AutoTweet (Playwright)

on:
  schedule:
    - cron: "*/1 * * * *"   # dakikada bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu getir
        uses: actions/checkout@v4

      - name: Python kurulum
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          python -m pip install tweepy playwright "pdfminer.six==20231228"
          python -m pip show pdfminer.six
          python -m playwright install --with-deps chromium

      - name: Çalıştır
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py
