name: Run bot manually

on:
  workflow_dispatch:  # sadece manuel tetiklenir

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps & run
        run: |
          pip install --upgrade pip
          pip install playwright tweepy
          python -m playwright install --with-deps chromium
          python -u main.py
