name: Auto Tweet BIST Company News

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # her 5 dakikada bir

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # posted.json güncellemelerini push’lamak için
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure state file
        run: |
          mkdir -p data
          if [ ! -f data/posted.json ]; then echo "[]" > data/posted.json; fi

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python main.py

      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update posted.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
